-- 시퀀스 삭제
DROP SEQUENCE USER_SEQ;
DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE NOTICE_IMAGE_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE USER_SEQ;
CREATE SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICE_IMAGE_SEQ;

-- 테이블 삭제
DROP TABLE NOTICE_IMAGE_T;
DROP TABLE NOTICE_T;
DROP TABLE USER_T;

-- 회원 테이블
CREATE TABLE USER_T (
	USER_NO	        NUMBER	            NOT NULL,
    ID              VARCHAR2(20 BYTE)	NOT NULL,
	PW	            VARCHAR2(64 BYTE)	NOT NULL,
	NAME	        VARCHAR2(50 BYTE)	NULL,
	GENDER	        VARCHAR2(2 BYTE)	NULL,
    EMAIL           VARCHAR2(20 BYTE)   NULL,
	HP	        VARCHAR2(15 BYTE)	NULL,
    HP_SMS_YN   VARCHAR2(20 BYTE)   NULL,
	JOINED_AT	    DATE	            NULL
);

-- 공지
CREATE TABLE NOTICE_T (
	NOTICE_NO	NUMBER	            NOT NULL,
	TITLE	    VARCHAR2(500 BYTE)	NOT NULL,
	CONTENTS	CLOB	            NULL,
	HIT	        NUMBER	            NULL,
	CREATED_AT	VARCHAR2(30 BYTE)	NULL
);

-- 공지 이미지
CREATE TABLE NOTICE_IMAGE_T (
	NOTICE_NO	        NUMBER	            NOT NULL,
	IMAGE_PATH	        VARCHAR2(100 BYTE)	NULL,
	FILESYSTEM_NAME 	VARCHAR2(100 BYTE)	NULL
);

-- PK
ALTER TABLE USER_T ADD CONSTRAINT PK_USER_T PRIMARY KEY (USER_NO);

ALTER TABLE NOTICE_T ADD CONSTRAINT PK_NOTICE_T PRIMARY KEY (NOTICE_NO);

-- FK

ALTER TABLE NOTICE_IMAGE_T ADD CONSTRAINT FK_NOTICE_T_TO_NOTICE_IMAGE_T_1 FOREIGN KEY (NOTICE_NO) 
REFERENCES NOTICE_T (NOTICE_NO) ON DELETE CASCADE;

------ INSERT ------

-- 반드시 모든 sql쿼리 하나라도 수정하면, 전체 쿼리 F5로 재실행 해야함.
-- 이전에 실행했던 쿼리에 수정 전 쿼리가 있으면, 실제 웹에서 동작시 에러남.

INSERT INTO USER_T VALUES(USER_SEQ.NEXTVAL, 'pyj4718', STANDARD_HASH('1735', 'SHA256'), 'pb마스터', 'M', 'pb@naver.com', 01013134545, 'Y', TO_DATE('250207', 'YYMMDD'));