DROP TABLE IF EXISTS `NOTICE_T`;

CREATE TABLE `NOTICE_T` (
	`NOTICE_NO`	NUMBER	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`TITLE`	VARCHAR2(500 BYTE)	NOT NULL,
	`CONTENTS`	CLOB	NULL,
	`HIT`	NUMBER	NULL,
	`CREATED_AT`	VARCHAR2(30 BYTE)	NULL
);

DROP TABLE IF EXISTS `USER_T`;

CREATE TABLE `USER_T` (
	`USER_NO`	NUMBER	NOT NULL,
	`EMAIL`	VARCHAR2(100 BYTE)	NOT NULL,
	`PW`	VARCHAR2(64 BYTE)	NOT NULL,
	`NAME`	VARCHAR2(50 BYTE)	NULL,
	`GENDER`	VARCHAR2(2 BYTE)	NULL,
	`MOBILE`	VARCHAR2(15 BYTE)	NULL,
	`JOINED_AT`	DATE	NULL
);

DROP TABLE IF EXISTS `NOTICE_IMAGE_T`;

CREATE TABLE `NOTICE_IMAGE_T` (
	`NOTICE_NO`	NUMBER	NOT NULL,
	`IMAGE_PATH`	VARCHAR2(100 BYTE)	NULL,
	`FILESYSTEM_NAME`	VARCHAR2(100 BYTE)	NULL
);

ALTER TABLE `NOTICE_T` ADD CONSTRAINT `PK_NOTICE_T` PRIMARY KEY (
	`NOTICE_NO`
);

ALTER TABLE `USER_T` ADD CONSTRAINT `PK_USER_T` PRIMARY KEY (
	`USER_NO`
);

