# Connection Pool, 오라클DB 연결 정보
spring:
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
      username: PB
      password: 1735

  thymeleaf:
    cache: false  #어플 재실행 없이 실시간 타임리프 반영이기에, 배포시에는 설정 지우거나, 반드시 true 로 바꿔줘야함

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
        
  messages:
    encoding: UTF-8


# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml

# character encoding, session, port
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800
      tracking-modes: cookie

# jasypt
  #jasypt:
    # encryptor:
  #  password: encryptKey